<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>name.bindul.bls.dm</groupId>
	<artifactId>bls-dm</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>Bowling League Stats :: Data Manager</name>
	<scm>
		<connection>scm:git:https://github.com/bindul/bls-dm.git</connection>
		<developerConnection>scm:git:https://github.com/bindul/bls-dm.git</developerConnection>
		<url>https://github.com/bindul/bls-dm</url>
	</scm>
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.14.0</version>
					<inherited>true</inherited>
					<configuration>
						<optimize>true</optimize>
						<source>${dev.java.version}</source>
						<target>${dev.java.version}</target>
						<encoding>${project.build.sourceEncoding}</encoding>
						<annotationProcessorPaths>
							<path>
								<groupId>org.projectlombok</groupId>
								<artifactId>lombok</artifactId>
								<version>${lombok.version}</version>
							</path>
						</annotationProcessorPaths>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-toolchains-plugin</artifactId>
					<version>3.2.0</version>
					<executions>
						<execution>
							<goals>
								<goal>toolchain</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
						<toolchains>
							<jdk>
								<version>${dev.java.version}</version>
								<vendor>eclipse</vendor>
							</jdk>
						</toolchains>
					</configuration>
				</plugin>
				<!--This plugin's configuration is used to store Eclipse m2e settings 
					only. It has no influence on the Maven build itself. -->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.apache.maven.plugins</groupId>
										<artifactId>maven-toolchains-plugin</artifactId>
										<versionRange>[1.1,)</versionRange>
										<goals>
											<goal>toolchain</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore />
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
	<dependencyManagement>
		<dependencies>
			<dependency>
	  			<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
				<scope>provided</scope>
	  		</dependency>
	  		<dependency>
	  			<groupId>org.xerial</groupId>
	  			<artifactId>sqlite-jdbc</artifactId>
	  			<version>3.51.0.0</version>
	  		</dependency>
		</dependencies>
	</dependencyManagement>
	<properties>
		<dev.java.version>25</dev.java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<lombok.version>1.18.38</lombok.version>
	</properties>
	<modules>
		<module>bls-dm-core</module>
		<module>bls-dm-store-sqlite</module>
		<module>bls-dm-export-site</module>
		<module>bls-dm-ui-swt</module>
		<module>bls-dm-app</module>
	</modules>
</project>
