# Externalized UI Text Labels
app.title=Bowling League Stats - Data Manager

app.exit.alert.title=BLS - Data Manager
app.exit.alert.content-text=A repository is open, potential for data loss. Do you wish to exit?

menu.file=File
menu.file.new=New Repository
menu.file.open=Open Repository
menu.file.recent=Recent Repositories
menu.file.close=Close Repository
menu.file.exit=Exit
menu.file.repo.type.local.file.sqllite=SQLite Local DB

menu.export=Export
menu.export.bls-site=BLS Website Format

menu.help=Help
menu.help.about=About
menu.help.about.dialog.build-label=Build :\ \