# Externalized UI Text Labels
app.title=Bowling League Stats - Data Manager

app.exit.alert.title=BLS - Data Manager
app.exit.alert.content-text=A repository is open, potential for data loss. Do you wish to exit?

menu.file=File
menu.file.new=New Repository
menu.file.open=Open Repository
menu.file.recent=Recent Repositories
menu.file.close=Close Repository
menu.file.exit=Exit
menu.file.init.error.title=Unable to start BLS: DM
menu.file.init.error.message=Error initializing resource store(s)

menu.export=Export
menu.export.bls-site=BLS Website Format

menu.help=Help
menu.help.about=About
menu.help.about.dialog.build-label=Build :\ \

repo.type.local.file.sqllite=SQLite Local DB

action.new.remote.unsupported=BLS:DM does not support remote file locations yet
action.new.local.title=Create New 
action.new.local.overwrite.title=Confirm Overwrite
action.new.local.overwrite.header=File already exists:\ \ 
action.new.local.overwrite.content=Do you want to overwrite the existing file?
action.new.local.task.title=Create new repository
action.new.local.task.in-progress=Creating new local repository:\ \ 
action.new.local.task.completed=Created new local repository:\ \  
action.new.local.task.failed=Failed to:\ \ 
action.new.local.error-dialog.title=Error creating new BLS Repository
action.new.local.error-dialog.message=Error creating DB:\ \ 
action.open.remote.unsupported=BLS:DM does not support remote file locations yet
action.open.local.task.title=Open existing repository
action.open.local.task.in-progress=Opening local repository:\ \ 
action.open.local.task.completed=Opened local repository:\ \  
action.open.local.task.failed=Failed to:\ \ 
action.open.local.error-dialog.title=Error opening BLS Repository
action.open.local.error-dialog.message=Error opening DB:\ \ 
action.close.task.title=Close repository
action.close.task.in-progress=Closing repository
action.close.task.completed=Closed repository
action.close.task.failed=Failed to:\ \ 
action.close.error-dialog.title=Error opening BLS Repository
action.close.error-dialog.message=Error opening DB:\ \ 

