-- Bowling Center
CREATE TABLE BOWLING_CENTER (
	CENTER_ID TEXT NOT NULL,
	NAME TEXT NOT NULL,
	IS_ACTIVE INTEGER DEFAULT (1) NOT NULL CHECK (IS_ACTIVE IN (0, 1)),
	LOCATION TEXT,
	CONSTRAINT BOWLING_CENTER_PK PRIMARY KEY (CENTER_ID)
) STRICT;